# Site settings
title: "Text Only"
description: "A text-only list of text-only websites. Easy on your bandwidth & your eyeballs. Updated when the time feels right."
version: "0.1"
size: "20k"

# Build settings
markdown: kramdown

# Exclude this stuff
exclude: [node_modules, gulpfile.js, package-lock.json, package.json, Gemfile.lock, Gemfile, README.md]

# Gems
gems:
  - jekyll-seo-tag
